# Generated by Django 4.1.3 on 2022-11-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
            insert into store_collection (title)
            values ('test')
        ""","""
            delete from store_collection where title='test'
        """)
    ]
